### ISSUE TITLE
PlaybackControls enchance

### ISSUE THREAD

**Issue by mike623** [alexanderwallin/react-player-controls#15]
Great lib. You save my life time. However I suggest that add flag to `PlaybackControls` (e.g `showNext` ) to control display next/prev button although I can handle using css

**Comment by alexanderwallin** [comment]
Thanks, @mike623! Glad you're making use of it.

That sounds like a reasonable feature to me.

**Comment by alexanderwallin** [comment]
`showPrevious` and `showNext` props were added in https://github.com/alexanderwallin/react-player-controls/commit/2731ede1f0d4004577be01b7edfed9e676f3d807, published in `0.5.14`.
