### ISSUE TITLE
onSeek time is NaN

### ISSUE THREAD

**Issue by valentinvichnal** [alexanderwallin/react-player-controls#20]
Nice library, the slider is awesome.
On Internet Explorer the ProgressBar's onSeek/onSeekStart/onSeekEnd time argument is always NaN.

**Comment by alexanderwallin** [comment]
Thanks for reporting, @valentinvichnal! I was wondering when IE would come with a surprise treat. :) Which version of IE are you using?

**Comment by valentinvichnal** [comment]
IE 11, but perhaps all older versions too.
The examples here doesn't work either.

**Comment by alexanderwallin** [comment]
Alright, I'll have a look.
