### ISSUE TITLE
Any license?

### ISSUE THREAD

**Issue by thekeenant** [alexanderwallin/react-player-controls#22]
I'd like to use it in a project, but without any explicit license the default copyright laws apply. If this is intended, that's fine too! Is it ISC as `package.json` indicates?

Awesome library :+1:

**Comment by thekeenant** [comment]
`LICENSE` file I suppose would be ideal, but I see it is ISC here as well: https://www.npmjs.com/package/react-player-controls.

Thanks!

**Comment by alexanderwallin** [comment]
I added a LICENSE file and published version `0.5.13` to npm.
