### ISSUE TITLE
Buttons looks oval to me, not circle

### ISSUE THREAD

**Issue by ummahusla** [alexanderwallin/react-player-controls#29]
I was reviewing the [docs](https://alexanderwallin.github.io/react-player-controls/) and found out that buttons are not a circle but oval. Not sure if it's a bug or a feature.

**Comment by ummahusla** [comment]
Made a PR to fix this, if it's a bug.

**Comment by alexanderwallin** [comment]
Well spotted, @ummahusla! I applied a simpler solution, just applying `display: block;` to `.Icon`. Thanks for the improvement.
