### ISSUE TITLE
Is it possible to pause video on time marker?

### ISSUE THREAD

**Issue by seleckis** [alexanderwallin/react-player-controls#34]
I need some event like `onEnter` for TimeMarker when I can pause the video. Is it possible right now? Or it is not the purpose the library is made for?

**Comment by alexanderwallin** [comment]
Hi @seleckis! I'm not sure I understand what you need to do. Could you explain it more in depth?

**Comment by seleckis** [comment]
I have a video which should start to play on some trigger (I use react-waypoint to catch the moment when user scrolls to some point). But it should pause after 10 second. Then scroll again and play more 10 seconds. And so on. I could set TimeMarkers for these 10 or whatever seconds episodes but how can I play/pause video on them? I know there is a `timeupdate` event which could be used for checking current time ([here is an example](https://stackoverflow.com/questions/19355952/make-html5-video-stop-at-indicated-time)), would be great to implement something similar in your library.

Simples workaround is to set ref and use `timeupdate` event which I have mentioned, but it not react-way.

**Comment by alexanderwallin** [comment]
I see! This library does not deal with any actual audio or video playback, it merely provides a set of handy UI components to build the interface with.

Good luck with your app!
