### ISSUE TITLE
Add user customisable icon feature

### ISSUE THREAD

**Issue by JPStrydom** [alexanderwallin/react-player-controls#36]
It would be nice to be able to set our own icons for play/pause/mute/etc. buttons.

**Comment by alexanderwallin** [comment]
Definitely! Thanks for pushing for it.

**Comment by JPStrydom** [comment]
Really helpful demo website BTW! Looking forward to the feature.

**Comment by alexanderwallin** [comment]
@JPStrydom I've just published `1.0.0-beta.0`. This version allows you to use whatever icons you want. See [the new README](https://github.com/alexanderwallin/react-player-controls) for details.

**Comment by alexanderwallin** [comment]
Closing this. Please reopen if issues with button icons occur.
