### ISSUE TITLE
Add buffer progress to `<ProgressBar />`

### ISSUE THREAD

**Issue by JPStrydom** [alexanderwallin/react-player-controls#37]
It would be awesome to be able to show how much a video has been pre-loaded by - such as YouTube does.

See the light-grey in the image below:

![capture](https://user-images.githubusercontent.com/25905330/38422345-ae669226-39aa-11e8-91c8-2ccac0633bb3.PNG)

**Comment by alexanderwallin** [comment]
Thanks for the suggestion, @JPStrydom! That would definitely make sense for this library to feature.

I'm doing a bit of library revamping a.t.m., but will keep this within eyesight.

**Comment by JPStrydom** [comment]
Awesome!
