### ISSUE TITLE
Bookmarks on the ProgressBar

### ISSUE THREAD

**Issue by MDrooker** [alexanderwallin/react-player-controls#40]
I may have missed this-
But is there a way to create "bookmarks" on the progressbar to quickly see points of interest in the video?

**Comment by alexanderwallin** [comment]
Hi there! Currently you cannot, but there is revamped version of the library on the way that let's you do pretty much whatever you want.

You can read [the future README here](https://github.com/alexanderwallin/react-player-controls/tree/composition).

**Comment by lparkermg** [comment]
Are there any updates on this? As I'm pretty interested in being able to use this functionality.

**Comment by alexanderwallin** [comment]
Not ready just yet, @lparkermg, but thanks for pushing!

**Comment by alexanderwallin** [comment]
@MDrooker @lparkermg I've just published `1.0.0-beta.0`. This version allows you to do whatever you want inside a progress bar. See [the new README](https://github.com/alexanderwallin/react-player-controls) for details.

**Comment by alexanderwallin** [comment]
I'm closing this for now. Please reopen if you're having issues implementing your bookmarks.
