### ISSUE TITLE
ProgressBar componentWillUnmount fires onSeekEnd

### ISSUE THREAD

**Issue by enderortak** [alexanderwallin/react-player-controls#44]
ProgressBar `componentWillUnmount` fires `onSeekEnd` and this is giving me trouble on the below scenario:

Before starting seek, I pause the playback and restart it if it was playing before the seek.
```
handleSeekStart = () => this.pausePlayback();
handleSeekEnd = () => { if (this.state.isPlaying) this.startPlayback(this.state.currentPoint); }
```

To handle unmounting of the component at the middle of a playback, I call my exit handler below:
```
handleExit =() => {
    this.setState({ isPlaying: false });
    this.stopPlayback();
  }
```
This works like that:
- Set playing state to false (async)
- Stop playback
- ProgressBar `componentWillUnmount` => `onSeekEnd` is called
- Check if playing state is true (I think since react `setState` function is async, playing state is still true here)
- playback starts again from the last point and keeps its progress in the background

Is there a way to detect if `onSeekEnd` is fired by `componentWillUnmount`? Or any other suggestions are welcomed.

**Comment by alexanderwallin** [comment]
This should probably only be fired if the user is currently dragging the slider value.

**Comment by enderortak** [comment]
@alexanderwallin thank you, checking the value will definitely help!
