### ISSUE TITLE
Perfect!

### ISSUE THREAD

**Issue by rijk** [alexanderwallin/react-player-controls#46]
_(Sorry for the issue spam)_ 

I came back to this page after a while because I had to modify the `ProgressBar` (to add annotations), and discovered the new direction:

> From a library point of view, creating and providing components like `<Player />` or `<ProgressBar />` tends to result in abstractions with tons of props, often preventing arbitrary customisation, whilst providing little real value. 

So just wanted to let you know the new direction for the package is exactly what I needed! Good move, thanks and keep up the good work!

**Comment by alexanderwallin** [comment]
This is my favourite kind of spam. Thank you! ❤️
